version: "3.1"

# Specify language
language: en

# Pipeline for NLU
pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "LexicalSyntacticFeaturizer"
- name: "CountVectorsFeaturizer"
- name: "DIETClassifier"
  epochs: 100
- name: "EntitySynonymMapper"
- name: "ResponseSelector"
  epochs: 100

# Policy configuration for dialogue management
policies:
- name: "MemoizationPolicy"
- name: "RulePolicy"
- name: "TEDPolicy"
  max_history: 5
  epochs: 100
assistant_id: 20250921-183625-rectilinear-overhang
